import Head from "next/head";
import { Comments } from "@/components/comments";
import { Main } from "@/styles/components";

export default function Home() {
  return (
    <>
      <Head>
        <title>Comments</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link
          rel="icon"
          type="image/png"
          sizes="32x32"
          href="/images/favicon-32x32.png"
        />
      </Head>
      <Main>
        <Comments />
      </Main>
    </>
  );
}
